### ISSUE TITLE
"KeyError: 'lists'' when executing script

### ISSUE THREAD

**Issue by lx4r** [phipsgabler/trello2md#13]
I tried converting my downloaded Trello data but got this error:
```
❯ python3 .\src\trello2md.py .\2021-06-06_Trello_data.json
Traceback (most recent call last):
  File "D:\Documents\Code\external\trello2md\src\trello2md.py", line 201, in <module>
    main()
  File "D:\Documents\Code\external\trello2md\src\trello2md.py", line 165, in main
    for lst in data['lists']:
KeyError: 'lists'
```

My Python version is 3.9.5 and I'm on Windows 10. What can I do to resolve this?
Thanks in advance for the help :).

**Comment by phipsgabler** [comment]
TBH, I haven't used the script for quite some time, and my first guess would have been that Trello have changed their JSON scheme.

But this doesn't seem to be the case, at least for the existing board I tried.  Would you be able to post the JSON file you tried this on, stripped of actual data?  Or at least take a look at your file yourself (Firefox opens JSON files nicely)?
